### ISSUE TITLE
Install fails with many error messages. 

### ISSUE THREAD

**Issue by cellfreak** [MCPCapital/harmonizeproject#10]
Install fails with many error messages. 

E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: http_parser in /usr/local/lib/python3.7/dist-packages (0.9.0)
fatal: destination path 'python-mbedtls' already exists and is not an empty directory.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: certifi==2019.11.28 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 7)) (2019.11.28)
running install
running bdist_egg
running egg_info
writing src/python_mbedtls.egg-info/PKG-INFO
writing dependency_links to src/python_mbedtls.egg-info/dependency_links.txt
writing requirements to src/python_mbedtls.egg-info/requires.txt
writing top-level names to src/python_mbedtls.egg-info/top_level.txt
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/pk.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/_md.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/tls.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/x509.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/hkdf.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/exceptions.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/mpi.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/_random.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/_ringbuf.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/version.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/_platform.c' Cython extension (up-to-date)
skipping 'build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/cipher/_cipher.c' Cython extension (up-to-date)
reading manifest file 'src/python_mbedtls.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/python_mbedtls.egg-info/SOURCES.txt'
installing library code to build/3.7.3/bdist.linux-armv7l/egg
running install_lib
running build_py
running build_ext
building 'mbedtls.pk' extension
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c build/3.7.3/tes/pk.c -o build/3.7.3/temp.linux-armv7l-3.7/build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/pk.o
build/3.7.3/temp.linux-armv7l-3.7/pyrex/mbedtls/pk.c:788:10: fatal error: mbedtls/md_internal.h: No such file or directory
 #include "mbedtls/md_internal.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
./setup.sh: line 15: exit: N: numeric argument required
pi@raspberrypi:~/harmonizeproject $ ls
harmonize.py  LICENSE.md  python-mbedtls  README.md  setup.sh  videotest.py
pi@raspberrypi:~/harmonizeproject $ ls
harmonize.py  LICENSE.md  python-mbedtls  README.md  setup.sh  videotest.py
pi@raspberrypi:~/harmonizeproject $ sudo videotest.py
sudo: videotest.py: command not found
pi@raspberrypi:~/harmonizeproject $ sudo python videotest.py
Traceback (most recent call last):
  File "videotest.py", line 1, in <module>
    import cv2
ImportError: No module named cv2
pi@raspberrypi:~/harmonizeproject $ ls
harmonize.py  LICENSE.md  python-mbedtls  README.md  setup.sh  videotest.py
pi@raspberrypi:~/harmonizeproject $

**Comment by MCPCapital** [comment]
The first set of errors here are related to failing to compile mbedtls. The second error (related to videotest.py) indicates that OpenCV did not install correctly.

I think this is a duplicate issue of #7 and #8 discussing similar issues, so I will close this issue as a duplicate for now.

I apologize for the late reply, I will try to update the setup instructions this week.
