### ISSUE TITLE
libjpeg62 doesn't install 

### ISSUE THREAD

**Issue by AdrianTM** [MCPCapital/harmonizeproject#12]
It seems like there's a conflict between libjpeg62 and libjpeg62-turbo (on Buster):
```
aptitude why-not libjpeg62                                                      
libjpeg62-turbo Conflicts libjpeg62
```

Program seems to run withlout libjpeg62, is that needed? 

I also issued a pull request adding some dependencies that are no captured in setup.py
Also, isn't it better to install python3-http-parser instead of using pip install http_parser (I just wonder, don't know a lot about http-parser)

**Comment by gman77** [comment]
Had the same issue with buster , just remove the libjpeg62 from the setup.sh file and run.

**Comment by MCPCapital** [comment]
I will update the setup file and instructions accordingly. Thanks!
