### ISSUE TITLE
Hue App

### ISSUE THREAD

**Issue by ActofRage** [MCPCapital/HarmonizeProject#15]
Hello,
I have implemented everything so far and it runs flawlessly. Only I do not know where to open the Hue app. Where and what do I have to do? 
Thanks in advance!

**Comment by friis** [comment]
I assume your question is related to what now, how to use the code with an app interface

The way I use it is install pm2 on rasberypi keep the application alive 

On the android phone install rasberypi SSH(cost a few bugs) this allows you to make some costimized commands in a bottom

An then you have a nice system
