### ISSUE TITLE
Can’t connect to the Hue Bridge

### ISSUE THREAD

**Issue by jgeorge1983** [MCPCapital/HarmonizeProject#16]
Hi,

I cannot seem to connect to my hue hub, I get the below error:

> pi@raspberrypi:~/HarmonizeProject $ python3 ./harmonize.py
> I will use the bridge at  192.168.5.24
> Hue bridge not found. Mission failed, better luck next time

originally my hue hub was in 192.168.4.206, it’s all on the same network but I switched it and cleared the pi cache.  I have also done it on a brand new install.

I noticed a closed issue where someone suggests deleting the config.json file but I do not have the file.

Any ideas would be appreciated.

**Comment by bradleydworak** [comment]
Hi, sorry for the late reply, I'm circling back on open issues. The hue bridge network discovery method was updated since version 1.3.0 and now uses multicast DNS to detect any connected bridges. Please let me know if this fixes your issue. Thanks, Brad

**Comment by bradleydworak** [comment]
Closing issue, considered resolved due to upgrades.
