### ISSUE TITLE
Harmonizeproject detailed coding directions

### ISSUE THREAD

**Issue by restorept** [MCPCapital/harmonizeproject#16]
Hello. I'm a beginner with Raspberry Pi. It is up and running properly. Wondering if there are specific step-by-step instructions for beginners. I have all the hardware necessary to complete this project but need specific step-by-step instructions on where to enter the coding within  Raspberry Pi. Any help is most appreciated. Thank you!

**Comment by MCPCapital** [comment]
Hey I think the instructions are pretty robust as everything is meant to be entered into a terminal shell. We will try to flush out the instructions more this week and make them more 'noob-friendly'. Thanks for your input!

**Comment by restorept** [comment]
Really appreciate your help. Thanks!

**Comment by restorept** [comment]
Hello, Matthew. I'm following up to see if you have created "Noob" friendly
instructions for project. Eager to check out the final project. Thanks very
much for your time and efforts!

Thank you.

Steven L. Braverman

C*onsider the environment before printing this email*

CONFIDENTIALITY NOTICE: Please respect HIPPA regulations. This email
message, including any attachments, is for the sole use of the intended
recipient(s) and may contain confidential and privileged information. Any
unauthorized review, use, disclosure, or distribution is prohibited. If you
are not the intended recipient, please contact the sender by reply email
and destroy all copies of the original message.
