### ISSUE TITLE
Build process doesn't seem to work.

### ISSUE THREAD

**Issue by earlthesquirrel** [MCPCapital/HarmonizeProject#19]
I have attempted both paths you list on a Raspberry Pi running Ubuntu 20.04 and neither build path produces a harmonize.py that starts.  

Can you confirm that both install processes have been tested recently?  I'm trying to understand why I'm having such trouble, given that you seem to have very clear instructions (they were easy to follow).

There are a couple packages that it says it can't find (when running your install script) so I don't know if they've been recently retired/changed or not.   That's why I want to confirm that the install approaches have been tried recently from a clean install of the OS (that's where I started from)

Thanks!

**Comment by earlthesquirrel** [comment]
I have python 3.8.5 installed
And it's Ubuntu 20.04.2 LTS

Currently when I run I get the following errors:

I will use the bridge at  172.16.230.253
[ WARN:0] global /home/ubuntu/opencv/modules/videoio/src/cap_gstreamer.cpp (597) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ WARN:0] global /home/ubuntu/opencv/modules/videoio/src/cap_v4l.cpp (890) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
Press return to stopException in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./harmonize.py", line 237, in averageimage
    coords[0] = ((coords[0])+1) * w//2 #Translates x value and resizes to video aspect ratio
NameError: name 'w' is not defined
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./harmonize.py", line 320, in buffer_to_light
    for i in rgb_bytes:
NameError: name 'rgb_bytes' is not defined

**Comment by bradleydworak** [comment]
Hello,

Thanks for your comments, and my apologies for the late reply. It appears from your most recent post that the error lies not necessarily with improper installation, but rather the detection and/or ability to open a stream on dev/video0. This can happen for a number of reasons, most often not having a proper video signal present or something else running and already using the /dev/video0 designation. I've encountered such issues on my own despite having everything properly installed. One thing I want to update with the code is giving proper feedback when a video stream cannot be opened for whatever reason. Will look into this. Brad

**Comment by earlthesquirrel** [comment]
Ok, so in your instructions could this possibly be because I tried Ubuntu on a Raspberry Pi vs. Raspbian?  I was going to try loading Raspbian and following the instructions from there...  Not sure if that might generate more info.

**Comment by bradleydworak** [comment]
I've only worked with Ubuntu running on the R Pi 4, so not sure if Raspbian OS will shed any more light on the matter. First is to do a sanity check by running ``ls -ltrh /dev/video*`` and see if /dev/video0 is on the list. I plan to update the code to give feedback that /dev/video0 is actually available as opposed to just crashing.

**Comment by earlthesquirrel** [comment]
Ok, so I’m in a position to restart. Have you tested from scratch recently?  And can you point me towards the right SD card image to start with?

**Comment by bradleydworak** [comment]
I tested it with Ubuntu Desktop 64-bit 20.04.2 in January of 2021. Since then, the Raspberri Pi installer only lists a Ubuntu Desktop option for the latest 64-bit OS version, currently, 21.04. That said, there is a decision to be made on which Ubuntu version OS to best support (ex. LTS vs latest desktop version). For now, I think a reasonable strategy is to stick to latest Ubuntu Desktop version if that is the only default option given with the installer. I've noticed some issues not recognizing /dev/video0 when the user is not logged into the console with a desktop open.

**Comment by bradleydworak** [comment]
By the way `ls -ltrh /dev/video*` will provide a result that includes /dev/video0 when the OS properly detects a connected USB video card adapter.

**Comment by earlthesquirrel** [comment]
Ok, will install Ubuntu Desktop tomorrow at latest. I have exact same HW as you listed, so I suspect it should work close to identically.

**Comment by earlthesquirrel** [comment]
BTW I had tried 21.04 with first go around. From that installer.

**Comment by bradleydworak** [comment]
Hi @earlthesquirrel , were you able to compile properly? I was going to close this issue if everything is ok now. Thanks, Brad

**Comment by bradleydworak** [comment]
Will close this issue since the program has been tested and re-built on Ubuntu 22.04. If there is a build issue currently please open a new issue. Thanks!

**Comment by earlthesquirrel** [comment]
Just FYI — the build never worked for me.  I had identical hw as you listed, and prebuilt things never worked either.  I finally found a reasonably price Hue Sync hub which solved things.

**Comment by bradleydworak** [comment]
Ok, thanks for letting me know and giving the project a shot. Glad you
found a working solution.

Brad
