### ISSUE TITLE
Harmonizeproject detailed coding directions

### ISSUE THREAD

**Issue by MCPCapital** [MCPCapital/HarmonizeProject#2]
Originally reported by @restorept  {Restoring old issues}

"Hello. I'm a beginner with Raspberry Pi. It is up and running properly. Wondering if there are specific step-by-step instructions for beginners. I have all the hardware necessary to complete this project but need specific step-by-step instructions on where to enter the coding within Raspberry Pi. Any help is most appreciated. Thank you!"

**Comment by restorept** [comment]
Matthew,

Thank you so much for following up here! Really appreciated.
Unfortunately,  I am getting a broken link. Could the project have been
removed? Please see attached.

**Comment by MCPCapital** [comment]
Hey @restorept ! Our old repo got deleted due to some incident with GitHub. I've re-uploaded the code [at MCPCapital/HarmonizeProject](https://github.com/MCPCapital/HarmonizeProject/) and was just trying to re-create some of the issues and other work we lost.

**Comment by restorept** [comment]
Thanks for the follow up Matthew! I'll be checking it out this weekend.
Hopefully I can handle the technical issues within Raspberry Pi. I really
appreciate your attention!

Thank you.

Steven L. Braverman

C*onsider the environment before printing this email*

CONFIDENTIALITY NOTICE: Please respect HIPPA regulations. This email
message, including any attachments, is for the sole use of the intended
recipient(s) and may contain confidential and privileged information. Any
unauthorized review, use, disclosure, or distribution is prohibited. If you
are not the intended recipient, please contact the sender by reply email
and destroy all copies of the original message.
