### ISSUE TITLE
Only shows first frame / image then errors out

### ISSUE THREAD

**Issue by gotschi** [MCPCapital/harmonizeproject#32]
I always get this error,
Script connects successfully, turns Hue Gradient dark and then shows colors of picture / first frame.

`python3 harmonize.py -g 2 -i a.b.c.d -f bigbuckbunny.mp4`

Then this shows up:

```Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/HarmonizeProject/harmonize.py", line 378, in cv2input_to_buffer
    rgbframe = cv2.cvtColor(bgrframe, cv2.COLOR_BGR2RGB) #corrects BGR to RGB
cv2.error: OpenCV(4.5.1) ../modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'```

**Comment by bradleydworak** [comment]
Could you please provide more details regarding the video file (frame rate, resolution, etc.)? Thanks.

**Comment by gotschi** [comment]
sorry I'm not using the project anymore,
but the buckbunny.mp4 was from here:
http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

thank you anyway for this project!
