### ISSUE TITLE
Option to increase light's brightness

### ISSUE THREAD

**Issue by apoorvprecisely** [MCPCapital/harmonizeproject#35]
Wanted to know if there's an option or a parameter one can tweak to increase the intensity of light through the script. It works great ofcourse but I've noticed that the lights are dimmer compared to the app version of hue sync. Apologies if this is something obvious that I'm missing.

**Comment by bradleydworak** [comment]
That's a good observation regarding the brightness. There is no attempt to increase it from the raw input. I believe it could be normalized to the highest possible setting while keeping the color consistent.

**Comment by apoorvprecisely** [comment]
@bradleydworak I couldn't find any documentations regarding the calls you're doing. If you can point me to it, I can dig too

**Comment by bradleydworak** [comment]
@apoorvprecisely One option would be to incorporate a `cv2.COLOR_BGR2HSV` call on line 385, then maximize V (brightness) to 100, then convert that value to RGB.

**Comment by apoorvprecisely** [comment]
@bradleydworak this worked for me https://github.com/MCPCapital/HarmonizeProject/pull/36
have a look

**Comment by bradleydworak** [comment]
This looks fantastic. Any perceived increase in lag time with this
processing relative to the video?

**Comment by apoorvprecisely** [comment]
I see atleast .5 second delay, but can't say for sure if this is the cause, since my hardware could be different. Also my raspberry pi is old and doesn't have usb 3.0, so not sure if that's the cause

**Comment by bradleydworak** [comment]
Ok, thx for checking. I like your solution and will test it out soon. This
seems to be the most straightforward approach, including the added flag.
