### ISSUE TITLE
bridge = int(input()) Error (multiple bridges?)

### ISSUE THREAD

**Issue by pady1991** [MCPCapital/HarmonizeProject#5]
Hello,
I get the error:

"File "./harmonize.py", line 28, in <module>

import mbedtls

File "/usr/local/lib/python3.7/dist-packages/mbedtls/__init__.py", line 8, in <module>

import mbedtls.cipher as cipher

File "/usr/local/lib/python3.7/dist-packages/mbedtls/cipher/__init__.py", line 12, in <module>

from . import AES, ARC4, ARIA, CHACHA20, DES, DES3, Blowfish, Camellia, DES3dbl

File "/usr/local/lib/python3.7/dist-packages/mbedtls/cipher/AES.py", line 11, in <module>

from mbedtls.exceptions import TLSError

ModuleNotFoundError: No module named 'mbedtls.exceptions'"

Maybe you can help me

**Comment by MCPCapital** [comment]
Hello @pady1991 

I know just what this error is, and it is happening because I forgot to update the main script when re-releasing the project. (Our old Repo was deleted because of an incident at GitHub)

I will update the script now and it should be working within a few minutes. Thanks for calling this issue out!

Edit: Please try now, you should no longer get mbedtls errors!

**Comment by pady1991** [comment]
Thanks, that helped a lot :)
Now I get, the error when I want to start the program:
Traceback (most recent call last):
  File "./harmonize.py", line 88, in <module>
    (hueip,port),headers = findhue() or ((None,None),None)
  File "./harmonize.py", line 52, in findhue
    bridge = int(input())   
ValueError: invalid literal for int() with base 10: ''

I pushed the buttons on the bridge many times, it don't work.
Should I make at first an Entertainment Area and then I start the program?

**Comment by MCPCapital** [comment]
@pady1991 Do you have multiple bridges? Line 52 is only invoked if you have more than one bridge on your network. I added that in but wasn't able to test it as I only have one bridge on hand. Line 88 is then erring because the bridge and it's IP weren't defined..
