### ISSUE TITLE
Finds bridge and then doesn't

### ISSUE THREAD

**Issue by erocm123** [MCPCapital/HarmonizeProject#6]
I get this message after a few seconds:

```
I will use the bridge at  192.168.1.75
Hue bridge not found. Mission failed, better luck next time
```

After it finds the bridge it only gives a few seconds to push the button (it never asks me to though - not sure if it is supposed to), but then it just says the bridge isn't found. 

Any help would be appreciated.

**Comment by MCPCapital** [comment]
Hey if it has never asked you to push the button (or you never did so successfully) you may have a corrupt `client.json` file.

Can you try removing that file? `cd` into the harmonizeproject directory and run `rm client.json`

Then try running it again and linking the bridge. Hopefully that will fix this issue!

**Comment by erocm123** [comment]
Thanks for the suggestion. I did not see a client.json file so I don't think this is the issue. Maybe there is something wrong with my setup. I have a Raspberry Pi 4 with a fresh install of raspbian. Then I clone the repository and run the setup script. Then run screen and go to the directory and run the harmonize.py script. This sounds like the way you have done it so there is probably something unique about my network that is causing problems.
