### ISSUE TITLE
Hardware Question: HDMI Video Capture

### ISSUE THREAD

**Issue by DarkPhoenix07** [MCPCapital/harmonizeproject#6]
Hello,
First off, thanks for doing this. Can't wait to see it in action!
I just wanted to confirm before I bought anything, how important is the HDMI pass-through for the capture card? It seems it needs the HDMI input from the splitter then connects via USB to the Pi.
Also, how important is USB 3.0 over 2.0? As I live in Australia I don't have access to many options. I'm looking at this one. Please let me know if there are any glaring issues.
https://cplonline.com.au/simplecom-da315-hdmi-to-usb-2-0-video-capture-card-full-hd-1080p-for-live-streaming-recording.html 
Since this allows 4k input, can I use a 4k splitter? Having the downscaling seems to increase the price significantly.

In your experience, does adding a splitter reduce quality or increase input lag? I'm going to buy this one
https://www.radioparts.com.au/product/64510014/hdmi2spv2-18gbps-2-way-hdmi-splitter-1-in-2-out-slim-hdmi-2.0#.XytQEigzZPY

Thanks again, and sorry I'm a bit of a noob!

**Comment by THATDONFC** [comment]
I'm curious as well. I purchased [this capture device](https://www.amazon.com/gp/product/B08BZQQQZS/) which accepts a 4k input and outputs at 1080. I'm going to test it and see if it works without the splitter. First I need to get this installed without errors though!

**Comment by MCPCapital** [comment]
Hello and thanks for your interest!

A USB2.0 Card will work, just slightly less well as you'll get lower FPS, maybe by about 15% by a backhand estimate.

You can try using a capture card that has a loop through output, but in my experience that loop through induces substantial delay. I only tried two cards though so feel free to try something and report back what works for you!
