### ISSUE TITLE
Setup issue with Open CV2

### ISSUE THREAD

**Issue by elmoellie** [MCPCapital/harmonizeproject#8]
Using Pi 3B, after running setup successfully, attempting to run harmonize.py bring up import error 

pi@raspberrypi:~/Hue $ ./harmonize.py
Traceback (most recent call last):
  File "./harmonize.py", line 26, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
pi@raspberrypi:~/Hue $

**Comment by AdrianTM** [comment]
apt install  python-opencv

**Comment by MCPCapital** [comment]
This seems to be an issue with the install of OpenCV. We are currently troubleshooting this and plan on updating the install instructions this week. I am closing this for now as a duplicate of #7 . Please comment there if you still encounter issues. Thanks!
