### ISSUE TITLE
Setup compabitility question

### ISSUE THREAD

**Issue by kratoskat** [MCPCapital/harmonizeproject#9]
So i'm a noob at this and trying to get my head around everything. Your examples only mention using external devices such as PS4 and the TV is an output but my set up is a bit different and i was wondering if you could advise on how to adapt this to work on mine.

There's reasoning behind the madness, mostly because it's a mixture of old and new tech and 4k and HD devices.

- I got 3 devices plugged in to a 4K TV via HDMI
    Firestick
    PS4 
    V6 box

- HDMI ARC from TV to AV Receiver to feed audio via HDMI from tv 
- Chromecast plugged into AV receiver via HDMI

I can use any one of those devices at any point to watch video.

The ideal would have been TV to Splitter out to Capture Card or AV Receiver (or the other way around) but as far as i know you can't split an ARC cable. 

Would you be able to advice whether this project is adaptable to my setup?

**Comment by MCPCapital** [comment]
The ARC output doesn't actually output any video, just audio, so its impossible to use that TV Out for video purposes. Our project would work, however, it will only work on one device at a time. Your fire stick or PS4 would take the place of 'HDMI Input' on the diagram in the Readme. If you want to use it with other devices, you'd need to either manually switch the HDMI cables or purchase an HDMI switcher to essentially virtually do it for you.

Closing this for now but feel free to reopen if you have more questions related to this topic. Thanks!
